version: '3'
services:
  client:
    build: ./client
    restart: unless-stopped
    ports:
      - '4321:4321'

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - '3000:3000'
